### ISSUE TITLE
Error when using stdin

### ISSUE THREAD

**Issue by oliversturm** [coderaiser/minify#48]
I have this in `file.js`:

```js
function hello() { 
	if (2 > 3) 
		console.log('for real');
}
```

I can run minify and pass the filename:

```shell
> minify file.js
[ 'function hello(){0}' ]
>
```

But I can't pass in the content through stdin:

```shell
> cat file.js | minify --js
TypeError: minify[name](...).then is not a function
    at processStream (/home/sturm/.nvm/versions/node/v8.11.3/lib/node_modules/minify/bin/minify.js:68:10)
    at Socket.read (/home/sturm/.nvm/versions/node/v8.11.3/lib/node_modules/minify/bin/minify.js:39:9)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at onEofChunk (_stream_readable.js:492:3)
    at readableAddChunk (_stream_readable.js:220:5)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:626:8)
>
```

**Comment by hanxiao** [comment]
got same issue

**Comment by coderaiser** [comment]
Thank you 🙂, fixed with 06b1b0b, landed in [v4.0.2](https://github.com/coderaiser/minify/releases/tag/v4.0.2) 🎉

**Comment by mwcz** [comment]
@coderaiser Unfortunately I'm still seeing this in v4.0.2 and on master.

Repro:

```
git clone https://github.com/coderaiser/minify.git
cd minify
npm install
cd bin
echo "body { color: #ffffff; }" | ./minify.js --css
```

Result:

```
TypeError: minify[name](...).then is not a function
    at processStream (/home/mclayton/projects/minify/bin/minify.js:68:10)
    at Socket.read (/home/mclayton/projects/minify/bin/minify.js:39:9)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at onEofChunk (_stream_readable.js:512:7)
    at readableAddChunk (_stream_readable.js:232:5)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:125:12)
```

**Comment by coderaiser** [comment]
🔨 Fixed with c4fe38f, landed in [v4.0.3](https://github.com/coderaiser/minify/releases/tag/v4.0.3) 🎉

**Comment by mwcz** [comment]
:+1: works like a charm.
